# Generated by Django 5.0.6 on 2024-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=400)),
                ('inStock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=60)),
                ('image', models.TextField(max_length=5112)),
            ],
        ),
    ]
